/**
 * RFC 9562 UUID version 7 generation for domain identifiers.
 *
 * The timestamp and random payload are assembled in the application so an ID
 * is available before persistence. The random payload is advanced whenever
 * two IDs share a timestamp, which keeps IDs generated by this process in
 * lexicographical order as well as making collisions impractical.
 */

const UUID_V7_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MAX_UUID_V7_TIMESTAMP = 0xffffffffffff;
const MAX_RANDOM_A = 0xfff;

declare const UUID_V7_BRAND: unique symbol;

/** A UUID string whose version and variant bits are known to be UUIDv7. */
export type UuidV7 = string & {
  readonly [UUID_V7_BRAND]: "UuidV7";
};

interface MonotonicState {
  timestamp: number;
  /** The 12-bit rand_a field from RFC 9562. */
  randomA: number;
  /** The 62-bit rand_b field from RFC 9562, stored big-endian. */
  randomB: Uint8Array;
}

let monotonicState: MonotonicState | undefined;

function randomBytes(length: number): Uint8Array {
  const cryptoApi = globalThis.crypto;

  if (!cryptoApi?.getRandomValues) {
    throw new Error(
      "UUIDv7 generation requires a runtime with crypto.getRandomValues",
    );
  }

  const bytes = new Uint8Array(length);
  cryptoApi.getRandomValues(bytes);
  return bytes;
}

function createRandomState(timestamp: number): MonotonicState {
  const bytes = randomBytes(10);

  return {
    timestamp,
    randomA: ((bytes[0] << 4) | (bytes[1] >>> 4)) & MAX_RANDOM_A,
    randomB: Uint8Array.from([
      bytes[2] & 0x3f,
      bytes[3],
      bytes[4],
      bytes[5],
      bytes[6],
      bytes[7],
      bytes[8],
      bytes[9],
    ]),
  };
}

/**
 * Advances the 74-bit random payload in UUID byte order.
 *
 * Returns false only when both random fields are exhausted. That case is
 * handled by moving the timestamp forward by one millisecond.
 */
function incrementRandomPayload(state: MonotonicState): boolean {
  for (let index = state.randomB.length - 1; index >= 0; index -= 1) {
    if (state.randomB[index] < 0xff) {
      state.randomB[index] += 1;
      return true;
    }

    state.randomB[index] = 0;
  }

  if (state.randomA < MAX_RANDOM_A) {
    state.randomA += 1;
    return true;
  }

  state.randomA = 0;
  return false;
}

function nextMonotonicState(now: number): MonotonicState {
  if (!monotonicState) {
    monotonicState = createRandomState(now);
    return monotonicState;
  }

  // Keep the last timestamp on clock rollback. Advancing the random payload
  // preserves ordering without exposing a timestamp older than the previous
  // ID generated by this process.
  if (now > monotonicState.timestamp) {
    monotonicState = createRandomState(now);
    return monotonicState;
  }

  if (incrementRandomPayload(monotonicState)) {
    return monotonicState;
  }

  if (monotonicState.timestamp >= MAX_UUID_V7_TIMESTAMP) {
    throw new Error("UUIDv7 timestamp space exhausted");
  }

  monotonicState.timestamp += 1;
  return monotonicState;
}

function writeTimestamp(bytes: Uint8Array, timestamp: number): void {
  let remaining = timestamp;

  for (let index = 5; index >= 0; index -= 1) {
    bytes[index] = remaining % 0x100;
    remaining = Math.floor(remaining / 0x100);
  }
}

function formatUuid(bytes: Uint8Array): string {
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0"));

  return [
    hex.slice(0, 4).join(""),
    hex.slice(4, 6).join(""),
    hex.slice(6, 8).join(""),
    hex.slice(8, 10).join(""),
    hex.slice(10, 16).join(""),
  ].join("-");
}

function buildUuid(state: MonotonicState): UuidV7 {
  const bytes = new Uint8Array(16);
  writeTimestamp(bytes, state.timestamp);

  // Version 7 occupies the high nibble of byte 6; rand_a occupies the rest.
  bytes[6] = 0x70 | (state.randomA >>> 8);
  bytes[7] = state.randomA & 0xff;

  // RFC 9562's UUID variant is binary 10 in the two most-significant bits.
  bytes[8] = 0x80 | state.randomB[0];
  bytes.set(state.randomB.subarray(1), 9);

  return formatUuid(bytes) as UuidV7;
}

/**
 * Generates a UUIDv7 before persistence.
 *
 * Domain schemas should use this function as their application-side default
 * (`$defaultFn(generateUuidV7)` in Drizzle) or call it explicitly in a use
 * case before issuing INSERT.
 */
export function generateUuidV7(): UuidV7 {
  const now = Date.now();

  if (!Number.isSafeInteger(now) || now < 0 || now > MAX_UUID_V7_TIMESTAMP) {
    throw new Error("Current time cannot be represented by UUIDv7");
  }

  return buildUuid(nextMonotonicState(now));
}

/** Returns true when a string has UUIDv7 version and RFC 9562 variant bits. */
export function isUuidV7(value: string): value is UuidV7 {
  return UUID_V7_PATTERN.test(value);
}

/** Extracts the Unix timestamp in milliseconds encoded by a UUIDv7. */
export function getUuidV7Timestamp(value: string): number {
  if (!isUuidV7(value)) {
    throw new Error("Invalid UUIDv7");
  }

  let timestamp = 0;
  const hex = value.replaceAll("-", "").slice(0, 12);

  for (const pair of hex.match(/.{2}/g) ?? []) {
    timestamp = timestamp * 0x100 + Number.parseInt(pair, 16);
  }

  return timestamp;
}

/** Compatibility alias for callers that prefer a noun-first timestamp name. */
export const uuidV7Timestamp = getUuidV7Timestamp;

