/** Category contracts are shared with the accounts module through S02. */
export {
  ACCOUNT_STATUSES,
  ACCOUNT_STATUS_VALUES,
  CATEGORY_KINDS,
  CATEGORY_KIND_VALUES,
  CATEGORY_NAME_MAX_LENGTH,
  CATEGORY_STATUSES,
  COMMAND_ID_MAX_LENGTH,
  S02_ERROR_CODES,
  S02_ERROR_MESSAGES,
  S02_NAME_MAX_LENGTH,
  STATUS_FILTERS,
  STATUS_FILTER_VALUES,
  S02DomainError,
  AccountsCategoriesDomainError,
  DomainValidationError,
  type AccountStatus,
  type CategoryStatus,
  type ArchiveCategoryCommand,
  type CategoryArchiveValidationInput,
  type CategoryHierarchyNode,
  type CategoryKind,
  type CategoryParentValidationInput,
  type CategoryReadModel,
  type Category,
  type CategoryReparentingValidationInput,
  type CreateCategoryCommand,
  type ListCategoriesQuery,
  type ListCategoriesReadModel,
  type ListQuery,
  type S02Error,
  type S02ErrorCode,
  type S02ErrorField,
  type S02Result,
  type StatusFilter,
  type UpdateCategoryCommand,
} from "../accounts-categories/contracts";
